export const GLOSSAIRE = [
  { slug: 'roleplay-ia', term: 'Roleplay IA', def: "Mise en situation conversationnelle où un apprenant s'entraîne face à un personnage joué par une intelligence artificielle, par écrit ou à l'oral, puis reçoit un retour sur son comportement. Aussi appelé jeu de rôle IA ou simulation conversationnelle.", body: "<p>Le roleplay IA s'utilise en formation pour répéter des conversations professionnelles : feedback, gestion de conflit, négociation, vente, relation client. Le personnage réagit à ce que dit l'apprenant, ce qui distingue le roleplay IA d'un module e-learning à choix multiples.</p><p>Trois éléments composent une solution : le moteur de dialogue (texte, voix ou avatar), l'éditeur de scénarios (personnage, contexte, objectif) et l'analyse (feedback comportemental, score, suivi).</p><p>Voir le <a href=\"/roleplay-ia\">comparatif des solutions de roleplay IA</a>.</p>", related: ['simulation-ia', 'mise-en-situation', 'soft-skills'] },
  { slug: 'simulation-ia', term: 'Simulation IA (en formation)', def: "Reproduction d'une situation professionnelle par un système d'IA pour permettre la pratique sans risque. Le roleplay IA est une simulation IA centrée sur la conversation ; d'autres simulations portent sur des gestes techniques ou des décisions.", body: "<p>Le terme « simulateur IA » gagne du terrain dans les recherches françaises (simulateur d'entretien, simulateur commercial). En formation, il désigne le plus souvent un roleplay IA vocal.</p>", related: ['roleplay-ia', 'mise-en-situation'] },
  { slug: 'mise-en-situation', term: 'Mise en situation professionnelle', def: "Exercice pédagogique qui place l'apprenant dans une situation proche du réel pour observer et développer ses comportements. Historiquement animée par un formateur, elle peut aujourd'hui être jouée par une IA.", body: "<p>La mise en situation est le terme le plus utilisé par les responsables formation français ; « roleplay IA » en est la version outillée. Ses limites classiques (coût, planification, une seule répétition) sont celles que le roleplay IA cherche à lever.</p>", related: ['roleplay-ia', 'soft-skills'] },
  { slug: 'coaching-ia', term: 'Coaching IA', def: "Accompagnement individuel assisté ou délivré par une IA : questions de réflexion, préparation d'objectifs, entraînement à des situations. Se distingue du roleplay IA, qui simule un interlocuteur, même si les deux se combinent souvent.", body: "<p>Le coaching IA vient en complément du coaching humain : l'IA pour la disponibilité et la répétition, le coach pour la prise de recul et les situations complexes. Un comparatif dédié est prévu sur Guide RH.</p>", related: ['roleplay-ia'] },
  { slug: 'soft-skills', term: 'Soft skills', def: "Compétences comportementales et relationnelles (communication, écoute, gestion des émotions, coopération, adaptabilité), par opposition aux compétences techniques. Elles se développent par la pratique et le feedback.", body: "<p>Le roleplay IA vise précisément les soft skills qui s'exercent dans la conversation : donner un feedback, gérer un désaccord, convaincre, écouter.</p>", related: ['roleplay-ia', 'mise-en-situation'] },
  { slug: 'scorm', term: 'SCORM', def: "Standard d'échange entre un contenu de formation et un LMS. Un module SCORM s'ouvre dans le LMS et lui remonte une complétion et un score global.", body: "<p>Versions courantes : SCORM 1.2 et SCORM 2004. Suffisant pour suivre qui a fait l'exercice ; insuffisant pour analyser le détail des sessions, qui relève de xAPI.</p>", related: ['xapi', 'lms'] },
  { slug: 'xapi', term: 'xAPI (Tin Can)', def: "Standard qui décrit chaque action d'apprentissage sous la forme « acteur – verbe – objet » et la stocke dans un LRS. Permet de remonter le détail d'une session de roleplay IA (durée, critères, progression).", body: "<p>À privilégier si vous voulez analyser la progression des collaborateurs au-delà de la complétion.</p>", related: ['scorm', 'lms'] },
  { slug: 'lms', term: 'LMS / LXP', def: "Plateforme de gestion de la formation (LMS) ou d'expérience d'apprentissage (LXP) : catalogue, inscriptions, suivi, contenus. Le roleplay IA s'y intègre par lien, SCORM, LTI ou xAPI.", body: "<p>Voir la page <a href=\"/roleplay-ia/integration-lms\">intégration LMS</a> du comparatif.</p>", related: ['scorm', 'xapi'] },
  { slug: 'qualiopi', term: 'Qualiopi', def: "Certification qualité obligatoire pour les prestataires de formation qui veulent que leurs actions soient financées par des fonds publics ou mutualisés (OPCO, CPF). Un éditeur de roleplay IA certifié peut proposer des parcours finançables.", body: "<p>Voir la page <a href=\"/roleplay-ia/qualiopi-opco\">Qualiopi et OPCO</a> du comparatif.</p>", related: ['opco'] },
  { slug: 'opco', term: 'OPCO', def: "Opérateur de compétences : organisme paritaire qui finance la formation professionnelle des entreprises de sa branche. La prise en charge d'un roleplay IA passe par un parcours de formation certifié Qualiopi.", body: "", related: ['qualiopi'] },
  { slug: 'ai-act', term: 'AI Act (règlement européen sur l\'IA)', def: "Règlement de l'Union européenne qui classe les systèmes d'IA par niveau de risque et fixe des obligations de transparence, de documentation et de supervision humaine. Les usages RH d'évaluation des salariés sont classés à haut risque.", body: "<p>Voir la page <a href=\"/roleplay-ia/ai-act\">roleplay IA et AI Act</a> du comparatif.</p>", related: ['rgpd'] },
  { slug: 'rgpd', term: 'RGPD', def: "Règlement général sur la protection des données. Les sessions de roleplay IA contiennent des données personnelles de salariés ; leur hébergement, leur conservation et leurs sous-traitants doivent être documentés.", body: "<p>Voir la page <a href=\"/roleplay-ia/rgpd-hebergement\">RGPD et hébergement</a> du comparatif.</p>", related: ['ai-act'] },
];
